### ISSUE TITLE
Repo "visualization-api-examples" is deprecated. 

### ISSUE THREAD

**Issue by praveenshrivas** [looker/visualization-api-examples#1]
As the visualizations in the repo "**visualization-api-examples**" is already deprecated. 
And we were about to add the visualization " **https://github.com/looker/visualization-api-examples/tree/master/examples/matrix**" and "**https://github.com/looker/visualization-api-examples/tree/master/examples/calendar**" which is the the old repo.
Can you please let us know any other visualization which can be the substitute of above two. 

Thanks,
Praveen Shrivas

**Comment by RichardCzechowski** [comment]
@praveenshrivas I don't believe there are replacements for the two above for the time being. So if they work for you, by all means use them. The primary point behind the depreciation warning is that this repo is no longer really supported and I don't think anyone is actively monitoring it.
I'm going to go ahead and close this issue since it's not really an 'issue', but feel free to respond here.
